version: '3.8'
services:
  cat:
    container_name: cat
    image: node:12.18.3
    build:
      context: .
    networks:
      - my-net
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - .:/usr/src/cat/
    stdin_open: true
    tty: true
    expose:
      - '3000'
      - '3001'
    command: /bin/bash
networks:
  my-net:
    external: true
